[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"   
  framework = "vite"
  port = 8888
  targetPort = 5173

[build.environment]
  RECAPTCHA_MIN_SCORE = "0.5"
